title: python4004
iconURL: assets/hacker.png
theme: jekyll-theme-hacker

permalink: :slug

social:
  linkedin: karimnour
  github: karimnour

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 3545
google_analytics: UA-NNNNNNNN-N

